apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-list-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AmirBasiony/todo-list-GitOps-ArgoCD-K8s.git
    targetRevision: main
    path: K8s_manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: todo-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      automaticallySync: true
      