apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-list-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: 875506561855.dkr.ecr.us-east-1.amazonaws.com/todo-nodejs-app:v1.0.0.8
        ports:
        - containerPort: 4000
        env:
        - name: mongoDbUrl
          value: mongodb://mongo:27017/todolistDb
      imagePullSecrets:
        - name: ecr-creds

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-list-app
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30001
