apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-list-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: 875506561855.dkr.ecr.us-east-1.amazonaws.com/todo-nodejs-app:v1.0.0.9
        ports:
        - containerPort: 4000
        env:
        - name: mongoDbUrl
          value: mongodb://mongo:27017/todolistDb
      imagePullSecrets:
        - name: ecr-creds

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-list-app
spec:
  type: ClusterIP
  selector:
    app: todo  
  ports:
    - port: 4000
      targetPort: 4000

# kubectl port-forward --address-0.0.0.0 svc/argocd-server  8888:80 -n argocd
# kubectl port-forward --address-0.0.0.0 svc/todo-service  8080:4000 -n todo-list-app
      


